### ISSUE TITLE
Rename `recv()` and `sender()`

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/MQClient#33]
The names of the context-manager methods `recv()` and `sender()` leave much to be desired. It would be nice if the names made it obvious these methods were context managers. 

`recv()` produces a generator. `sender()` produces an instance with a method `send()` to call. `sender()` also looks like `send()`, which could be confusing.

In contrast, there is `recv_one()`, which is a context manager that directly produces a message.

Ideas in comments:

**Comment by ric-evans** [comment]
rename to `recv_stream()` and `send_stream()`

**Comment by ric-evans** [comment]
rename to `in_stream()` and `out_stream()`

**Comment by ric-evans** [comment]
rename to `sub()` and `pub()` (and `sub_one()`)

**Comment by jnbellinger** [comment]
Would "make_generator()" and "make_sender()" be confusing?

**Comment by ric-evans** [comment]
`make_pub()` and `make_sub()` (and `sub_one()`)

**Comment by ric-evans** [comment]
`open_pub()` and `open_sub()` (and `sub_one()`)

**Comment by dsschult** [comment]
> rename to `recv_stream()` and `send_stream()`

`recv_stream()` is actually fairly accurate, as it is a generator.  vs the send path is not, and also doesn't take a generator as input.

One thing I notice is that the `Queue` seems biased towards receiving messages.  That might be OK though, since `sub` clients tend to be more numerous in the `pub`/`sub` pattern.

So, for the send side, I might go with `open_pub()` and keep any send-specific methods under there.

**Comment by blinkdog** [comment]
I took a look at the code to put it back into brain cache and I think I understand what's going on.

I looked up Python library docs for `Queue` and `multiprocessing.Queue`:

https://docs.python.org/3/library/queue.html

https://docs.python.org/3/library/multiprocessing.html

Queue uses `get` and `put` in its API, and `multiprocessing.connection.Connection` objects have `recv` and `send` methods in their API. Normally I'd like to "do as the Romans do", but our API isn't quite as bare metal; we return 'an object that lets you do' rather than the data objects proper.

Stack Overflow kinda shrugs its shoulders as well:

Naming convention for context-manager classes ("with" blocks)
https://stackoverflow.com/q/19948457

I agree that `recv()` and `sender()` are a bit terse, and Python itself doesn't offer a strong convention on what to name something that gives you a context manager. Closest is maybe `open`, but that's probably because it's used in context manager examples. For that reason I think I like Ric's suggestion:

> `open_pub()` and `open_sub()` (and `sub_one()`)

Here the "open" part suggests you're getting something that you'll use in the way that we see in the unit tests:

```
    async with q.open_pub() as s:
        await s.send(data)
```

```
    async with q.open_sub() as recv_gen:
        recv_data = [d async for d in recv_gen]
        assert data == recv_data
```

For `recv_one` (for which we're considering `sub_one`), I'll say it feels a little weird to be a generator.

Normally, I think of generators as lazy iterators (or 'just in time' iterators, if you prefer), but the `_one` in the name implies 'There Can Be Only One!' which begs the question: If there will be only one, why is it coming from a generator?

If the method could be rewritten to async return the data from the message, maybe call it `get_one`?

Then again, I may be missing something about the larger context (no pun intended) where `sub_one` would play a role.

**Comment by ric-evans** [comment]
Thanks for your deep dive @blinkdog, you bring up many good points.

To comment on:

> For `recv_one` (for which we're considering `sub_one`), I'll say it feels a little weird to be a generator.
> 
> Normally, I think of generators as lazy iterators (or 'just in time' iterators, if you prefer), but the `_one` in the name implies 'There Can Be Only One!' which begs the question: If there will be only one, why is it coming from a generator?
> 
> If the method could be rewritten to async return the data from the message, maybe call it `get_one`?
> 
> Then again, I may be missing something about the larger context (no pun intended) where `sub_one` would play a role.

`recv_one` (as it's called currently) is a context manager that directly produces the message. The intention here is to be able to "pop the queue" without spending the cost of actually opening the stream, at least that was the intention. That said, this needs to be context manager because of necessary cleanup steps.

**Comment by dsschult** [comment]
Technically, I guess we could restructure some things to have all the recv code come off the class returned by the `open_sub()` context manager.  Maybe that makes more sense, to "open" the subscription with a context manager, then use it via either a streaming iterator, or the singular method (and ack/nack).

**Comment by dsschult** [comment]
Yeah, that's an annoying case.  I guess you could always raise an exception if you've got a message outstanding that hasn't been ack/nacked yet.

Or maybe we need to review why we need the non-iterator version.  It has its uses, but maybe we don't need to be that flexible?

**Comment by ric-evans** [comment]
I don't think we need to be that flexible

**Comment by ric-evans** [comment]
It looks like we've gravitated toward the "open" naming scheme: `open_pub()` and `open_sub()` 

And, I propose `open_sub_one()` for the other.
